name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.16', '1.17', '1.18', '1.19' ]
        gorm-version: [ 'v1.22.5', 'v1.23.10', 'v1.24.2' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install gorm
        run: go get gorm.io/gorm@${{ matrix.gorm-version }}
      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage
        uses: codecov/codecov-action@v3
